import Head from 'next/head';

const Home = () => {
	return (
		<div className='flex items-center justify-center w-screen h-screen bg-gray-900 text-white'>
			<Head>
				<title>Create Next App</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<div>Home</div>
		</div>
	);
};

export default Home;
